services:
  app:
    container_name: pki_2fa_app

    # Build the image from the current directory
    build:
      context: .
      dockerfile: Dockerfile

    # Expose API port
    ports:
      - "8080:8080"

    # Volume mounts
    volumes:
      # Named volumes â†’ persist seed + cron logs
      - seed-data:/data
      - cron-output:/cron

      # Mount key files (readonly)
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro

    # Environment variables
    environment:
      - TZ=UTC

    # Restart policy
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
