version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pki-totp-app
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
      - DATA_DIR=/data
      - STUDENT_PRIVATE_KEY=/app/student_private.pem
    volumes:
      - seed-data:/data
      - cron-output:/cron
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
